# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_approval',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacist_aproval',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
