# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0003_auto_20170813_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='approved_doctors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='approved_pharmacist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
