# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0004_auto_20170813_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, to='pharmeasyflow.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pharmacist',
            field=models.ManyToManyField(blank=True, null=True, to='pharmeasyflow.Pharmacist'),
        ),
    ]
