# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0005_auto_20170813_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_record',
            field=models.CharField(default='asdsad', max_length=200),
            preserve_default=False,
        ),
    ]
