# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0006_patient_medical_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='approved_doctors',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='approved_pharmacist',
        ),
        migrations.AddField(
            model_name='patient',
            name='requested_approval',
            field=models.TextField(blank=True, null=True),
        ),
    ]
