# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmeasyflow', '0009_auto_20170813_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record',
            field=models.CharField(default='ACIDITY', max_length=200),
        ),
    ]
